### ISSUE TITLE
Incorrect link on wiki page

### ISSUE THREAD

**Issue by chage** [nilenso/goose#112]
There is an incorrect link on page [Guide to Custom Metrics Backend](https://github.com/nilenso/goose/wiki/Guide-to-Custom-Metrics-Backend) of the Wiki.

> As a start, refer implementation of [StatsD](https://github.com/nilenso/goose/tree/main/src/goose/brokers/redis).

I think it should be `https://github.com/nilenso/goose/blob/main/src/goose/metrics/statsd.clj`?

**Comment by olttwa** [comment]
Thanks @chage for reporting this. I have updated the wiki with the correct link.

Please feel free to reach out in case you face any issues using Goose, or have any feature-requests.
